### ISSUE TITLE
 Method com/jetbrains/snakecharm/lang/psi/SmkWorkflowLocalrulesSection.getPresentation()Lcom/intellij/navigation/ItemPresentation; is abstract

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#145]
```
java.lang.AbstractMethodError: Method com/jetbrains/snakecharm/lang/psi/SmkWorkflowLocalrulesSection.getPresentation()Lcom/intellij/navigation/ItemPresentation; is abstract
	at com.jetbrains.snakecharm.lang.psi.SmkWorkflowLocalrulesSection.getPresentation(SmkPsiElements.kt)
	at com.jetbrains.snakecharm.lang.psi.impl.SmkWorkflowLocalrulesSectionImpl.getPresentation(SmkWorkflowLocalrulesSectionImpl.kt:18)
	at com.jetbrains.python.structureView.PyStructureViewElement.getPresentation(PyStructureViewElement.java:233)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.update(TreeElementWrapper.java:42)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:89)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:471)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:453)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:445)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:439)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:409)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:321)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:315)
```

**Comment by iromeo** [comment]
Similar issue
```
ava.lang.AbstractMethodError: Method com/jetbrains/snakecharm/lang/psi/SmkWorkflowLocalrulesSection.getIcon(I)Ljavax/swing/Icon; is abstract
	at com.jetbrains.snakecharm.lang.psi.SmkWorkflowLocalrulesSection.getIcon(SmkPsiElements.kt)
	at com.jetbrains.snakecharm.lang.psi.impl.SmkWorkflowLocalrulesSectionImpl.getIcon(SmkWorkflowLocalrulesSectionImpl.kt:20)
	at com.jetbrains.python.structureView.PyStructureViewElement$2.getIcon(PyStructureViewElement.java:267)
	at com.intellij.ide.projectView.PresentationData.updateFrom(PresentationData.java:187)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.update(TreeElementWrapper.java:42)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:89)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:471)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:453)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:445)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:439)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:409)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:321)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:315)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:335)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:585)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:479)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:445)
	at com.intellij.util.concurrency.Command$Processor.lambda$process$1(Command.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:126)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManage
```
