### ISSUE TITLE
Snakemake wrappers resolve/completion

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#18]
Resolve / completion from the configured wrappers repo

```
rule samtools_sort:
    input:
        "mapped/{sample}.bam"
    output:
        "mapped/{sample}.sorted.bam"
    params:
        "-m 4G"
    threads: 8
    wrapper:
        "0.0.8/bio/samtools_sort"
```

> Here, Snakemake will automatically downloads the corresponding wrapper from https://bitbucket.org/snakemake/snakemake-wrappers/src/0.0.8/bio/samtools_sort/wrapper.py.

> . Alternatively, e.g., for development, the wrapper directive can also point to full URLs, including URLs to local files with absolute paths file:// or relative paths file:. 

Update: Bitbucket wrappers deprecated (https://bitbucket.org/snakemake/snakemake-wrappers/src/62b507647dde?at=master) use GitHub repo (https://github.com/snakemake/snakemake-wrappers)

**Comment by iromeo** [comment]
E.g we could add reference on a string, see `http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/reference_contributor.html#define-a-reference-contributor` to provide completion/resolve for wrappers from `https://bitbucket.org/snakemake/snakemake-wrappers/src/master/` or any custom source.

Read about wrappers at `https://snakemake-wrappers.readthedocs.io/en/stable/`

**Comment by iromeo** [comment]
In case of local files - paths starts with `file://` prefix, e.g.:
```
rule foo:
  wrapper:
        f"file://{PIPELINE_PATH}/wrappers/bio/bismark/bismark"
```

also could be relative paths

**Comment by sharkovadarya** [comment]
Be wary of rate limits for request to repositories: https://confluence.atlassian.com/bitbucket/rate-limits-668173227.html

**Comment by iromeo** [comment]
API examples:
* Documentation popup: `SmkShadowSettingsDocumentation`

**Comment by iromeo** [comment]
Example:
```
rule virus_reference_genome_chromsizes:
    output: "indexes/{virus_genome}/{virus_genome}.chrom.sizes"
    log:    "indexes/{virus_genome}/{virus_genome}.chrom.sizes.log"
    input:  "indexes/{virus_genome}/{virus_genome}.2bit"
    message: "Indexes: Chrom sizes for {input}"
    shadow: "full"
    wrapper:
        "0.43.1/bio/ucsc/twoBitInfo"
```

**Comment by iromeo** [comment]
@SimonTsirikov 
Get exception when playing with `features/#18-resolve-completion-for-wrappers`
```
java.nio.file.NoSuchFileException: /github.com/snakemake/snakemake-wrappers/archive/master.zip
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at com.intellij.platform.templates.github.ZipUtil.unzip(ZipUtil.java:94)
	at com.jetbrains.snakecharm.codeInsight.completion.wrapper.SmkWrapperCrawler$runActivity$1$1.run(SmkWrapperCrawler.kt:30)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by iromeo** [comment]
Missing at the moment:
- [ ] Parse not only `wrappers.py` but also `meta.yaml` and collect keyword args and their descriptions
- [ ] Bundle wrappers should contain information about all wrappers releases, e.g. not all tools available in `latest` release or parameters could be changed. Otherwise, our completion/inspection will show false positives for such cases
- [ ] Not all wrapper params are obligatory. Maybe understand it from calls like `snakemake.get("key", default_value)` in wrappers.py or use some conventions in `meta.yaml`
- [ ] Documentation for section name (e.g input/output) that shows expected args for this section, not only documentation for wrapper.
- [ ] Load bundled wrappers storage object once for all projects/modules, not `per module`
- [ ] External documentation link in documentation popup doesn't work ok for `master/bio/multiqc`.
- [ ] Show all paramse extracted from wrapper sources in documentation popup
- [ ] Think of wrappers info auto-update, e.g. from TeamCity
- [ ] In case of using `file://`, collect such wrappers, parse&resolve params and add to project wrappers info 'storage'

**Comment by iromeo** [comment]
Initial support implemented, rest will be in `wrappers` milestone

**Comment by iromeo** [comment]
Seems not all mentioned in `Missing at the moment:` is extracted as issues
