### ISSUE TITLE
SnakemakeLexer: AIOOBE: Index -1 out of bounds for length 4

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#202]
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
	at gnu.trove.TIntArrayList.get(TIntArrayList.java:234)
	at gnu.trove.TIntStack.peek(TIntStack.java:88)
	at com.jetbrains.python.lexer.PythonIndentingProcessor.processIndent(PythonIndentingProcessor.java:379)
	at com.jetbrains.python.lexer.PythonIndentingProcessor.processLineBreak(PythonIndentingProcessor.java:356)
	at com.jetbrains.snakecharm.lang.parser.SnakemakeLexer.processLineBreak(SnakemakeLexer.kt:300)
	at com.jetbrains.python.lexer.PythonIndentingProcessor.processSpecialTokens(PythonIndentingProcessor.java:281)
	at com.jetbrains.python.lexer.PythonIndentingLexer.processSpecialTokens(PythonIndentingLexer.java:18)
	at com.jetbrains.snakecharm.lang.parser.SnakemakeLexer.advance(SnakemakeLexer.kt:191)
	at com.intellij.lang.impl.TokenSequence$Builder.performLexing(TokenSequence.java:86)
	at com.intellij.lang.impl.PsiBuilderImpl.performLexing(PsiBuilderImpl.java:188)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:161)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:115)
	at com.intellij.lang.impl.PsiBuilderFactoryImpl.createBuilder(PsiBuilderFactoryImpl.java:37)
	at com.jetbrains.python.psi.PyFileElementType.parseContents(PyFileElementType.java:87)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:198)
```

**Comment by iromeo** [comment]
To reproduce, 

1. create Snakefile:
```
import pandas as pd
from pipeline_util import collect_relative_paths

# First generate data_reads.tsv:
# python make_data_table.py config['fastq_dir'] fq.gz data_reads.tsv

df = pd.read_csv("data_reads.tsv", sep='\t')
config["DF"] = df

onstart:
    shell(
        'echo "TMPDIR=$TMPDIR"; '
        'echo "PATH=$PATH"; '
        'echo "TOOLS:"; '
        'echo   "PYTHON: $(which python)"; '
        'echo   "CONDA: $(which conda)"; '
        'echo   "SNAKEMAKE: $(which snakemake)"; '
        'echo   "PYTHON VERSION: $(python --version)"; '
        'echo   "CONDA VERSION: $(conda --version)"; '
        'echo   "SNAKEMAKE VERSION: $(snakemake --version)"'
    )

    print("Reads data:")
    df = config["DF"]
    samples = sorted(set(df["sample"].tolist()))
    # XXX print(f"Total files: {len(df)}")
    print("Total files: {}".format(len(df)))
    print("Samples: {}".format(len(samples)))
    print("    {}".format(samples))

# when using: snakemake -d <pipeline_dir> - this file is expected to be in pipeline_dir
# if -d isn't used, this file is expected to be in current directory (e.g. pipeline src)

configfile: "config.yaml"
workdir: config['work_dir']


config['FQ_RELATIVE_PATHS'] = collect_relative_paths(
    config['fastq_dir'], f"**/*.{config['fastq_ext']}"
)

include: "rules/raw_qc.smk"
include: "rules/bismark_align.smk"

rule all:
    input:
        rules.targets_raw_qc.input,
        rules.targets_bismark_align.input
```
2. try to comment 38-th line (`config['FQ_RELATIVE_PATHS'] ..) using `ctrl + /` action
