### ISSUE TITLE
Exception on opening raw files via URL

### ISSUE THREAD

**Issue by sharkovadarya** [JetBrains-Research/snakecharm#236]
Create a file with this line:  

    include: "https://bitbucket.org/snakemake/snakemake-wrappers/raw/0.36.0/bio/bcftools/call/wrapper.py"

And try to go to definition (standard hotkey Ctrl + B) on this URL. Normally an html file would be downloaded and opened. In this case we're downloading a raw `.py` file. Since it's a `.py` file, `PyInspectionSuppressor` processes it, and an exception is thrown:

```
java.lang.Throwable: Cannot find element among its parent' children. element: 'PyFile:wrapper.py'; parent: 'PsiDirectory:https://bitbucket.org/snakemake/snakemake-wrappers/raw/0.36.0/bio/samtools/view'; children: [];  file:PyFile:wrapper.py
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getChildIndex(SharedPsiElementImplUtil.java:136)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getPrevSibling(SharedPsiElementImplUtil.java:124)
	at com.intellij.psi.impl.source.PsiFileImpl.getPrevSibling(PsiFileImpl.java:310)
	at com.jetbrains.python.inspections.PyInspectionsSuppressor.isSuppressedForElement(PyInspectionsSuppressor.java:73)
	at com.jetbrains.python.inspections.PyInspectionsSuppressor.isSuppressedForParent(PyInspectionsSuppressor.java:65)
	at com.jetbrains.python.inspections.PyInspectionsSuppressor.isSuppressedFor(PyInspectionsSuppressor.java:53)
	at com.intellij.codeInspection.InspectionProfileEntry.isSuppressed(InspectionProfileEntry.java:154)
	at com.intellij.codeInspection.InspectionProfileEntry.isSuppressedFor(InspectionProfileEntry.java:69)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection.isSuppressedFor(SpellCheckingInspection.java:58)
	at com.intellij.codeInspection.SuppressionUtil.inspectionResultSuppressed(SuppressionUtil.java:179)
	at com.intellij.codeInspection.SuppressionUtil.inspectionResultSuppressed(SuppressionUtil.java:175)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.addDescriptorIncrementally(LocalInspectionsPass.java:406)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:61)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$1.registerProblem(LocalInspectionsPass.java:287)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection.addRegularDescriptor(SpellCheckingInspection.java:142)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection.access$000(SpellCheckingInspection.java:26)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$MyTokenConsumer.consume(SpellCheckingInspection.java:239)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$MyTokenConsumer.consume(SpellCheckingInspection.java:187)
	at com.intellij.spellchecker.inspections.BaseSplitter.addWord(BaseSplitter.java:46)
	at com.intellij.spellchecker.inspections.IdentifierSplitter.split(IdentifierSplitter.java:63)
	at com.intellij.spellchecker.inspections.WordSplitter.split(WordSplitter.java:51)
	at com.intellij.spellchecker.inspections.TextSplitter.doSplit(TextSplitter.java:52)
	at com.intellij.spellchecker.inspections.TextSplitter.split(TextSplitter.java:43)
	at com.intellij.spellchecker.inspections.PlainTextSplitter.split(PlainTextSplitter.java:94)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$MyTokenConsumer.consumeToken(SpellCheckingInspection.java:214)
	at com.jetbrains.python.spellchecker.PythonSpellcheckerStrategy$StringLiteralTokenizer.tokenize(PythonSpellcheckerStrategy.java:66)
	at com.jetbrains.python.spellchecker.PythonSpellcheckerStrategy$StringLiteralTokenizer.tokenize(PythonSpellcheckerStrategy.java:42)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection.tokenize(SpellCheckingInspection.java:121)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$1.visitElement(SpellCheckingInspection.java:105)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:75)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:292)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:260)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:257)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1163)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:65)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:263)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:196)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:115)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by iromeo** [comment]
Also in PyCharm 2020.2.1:
```
java.lang.Throwable: Cannot find element among its parent' children. element: 'PyFile:wrapper.py'; parent: 'PsiDirectory:https://bitbucket.org/snakemake/snakemake-wrappers/raw/0.36.0/bio/bcftools/call'; children: [];  file:PyFile:wrapper.py
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getChildIndex(SharedPsiElementImplUtil.java:118)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getPrevSibling(SharedPsiElementImplUtil.java:106)
	at com.intellij.psi.impl.source.PsiFileImpl.getPrevSibling(PsiFileImpl.java:338)
	at com.jetbrains.python.inspections.PyInspectionsSuppressor.isSuppressedForElement(PyInspectionsSuppressor.java:73)
	at com.jetbrains.python.inspections.PyInspectionsSuppressor.isSuppressedForParent(PyInspectionsSuppressor.java:65)
	at com.jetbrains.python.inspections.PyInspectionsSuppressor.isSuppressedFor(PyInspectionsSuppressor.java:53)
	at com.intellij.codeInspection.InspectionProfileEntry.isSuppressed(InspectionProfileEntry.java:157)
	at com.intellij.codeInspection.InspectionProfileEntry.isSuppressedFor(InspectionProfileEntry.java:69)
	at com.intellij.codeInspection.InspectionProfileEntry.isSuppressedFor(InspectionProfileEntry.java:63)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection.isSuppressedFor(SpellCheckingInspection.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.addDescriptorIncrementally(LocalInspectionsPass.java:419)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:59)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$1.registerProblem(LocalInspectionsPass.java:289)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection.addRegularDescriptor(SpellCheckingInspection.java:142)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection.access$000(SpellCheckingInspection.java:26)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$MyTokenConsumer.consume(SpellCheckingInspection.java:220)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$MyTokenConsumer.consume(SpellCheckingInspection.java:176)
	at com.intellij.spellchecker.inspections.BaseSplitter.addWord(BaseSplitter.java:46)
	at com.intellij.spellchecker.inspections.IdentifierSplitter.split(IdentifierSplitter.java:61)
	at com.intellij.spellchecker.inspections.WordSplitter.split(WordSplitter.java:52)
	at com.intellij.spellchecker.inspections.TextSplitter.doSplit(TextSplitter.java:54)
	at com.intellij.spellchecker.inspections.TextSplitter.split(TextSplitter.java:43)
	at com.intellij.spellchecker.inspections.PlainTextSplitter.split(PlainTextSplitter.java:102)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$MyTokenConsumer.consumeToken(SpellCheckingInspection.java:203)
	at com.jetbrains.python.spellchecker.PythonSpellcheckerStrategy$StringLiteralTokenizer.tokenize(PythonSpellcheckerStrategy.java:67)
	at com.jetbrains.python.spellchecker.PythonSpellcheckerStrategy$StringLiteralTokenizer.tokenize(PythonSpellcheckerStrategy.java:43)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection.tokenize(SpellCheckingInspection.java:121)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$1.visitElement(SpellCheckingInspection.java:104)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:294)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:263)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:155)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:147)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1105)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:57)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:266)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:191)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:113)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:80)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
