### ISSUE TITLE
Inspection: warn if user uses rule/checkpoint object in input instead of rules section

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#257]
E.g. quite hard to find an error in large project, which is actually in missing ".input" in latest rule dependency

![image](https://user-images.githubusercontent.com/72933/64351560-32f66a80-d003-11e9-9f71-910db3c66535.png)

Snakemake returns smth meaningless:
```
Full Traceback (most recent call last):
  File "/home/user/miniconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/rules.py", line 463, in _set_inoutput_item
    for i in item:
TypeError: 'RuleProxy' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/__init__.py", line 404, in snakemake
    print_compilation=print_compilation)
  File "/home/user/miniconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/workflow.py", line 743, in include
    exec(compile(code, snakefile, "exec"), self.globals)
  File "/mnt/stripe/rcherniatchik/_playground/pipeline/sources2/Snakefile", line 91, in <module>
  File "/home/user/miniconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/workflow.py", line 815, in decorate
    rule.set_input(*ruleinfo.input[0], **ruleinfo.input[1])
  File "/home/user/miniconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/rules.py", line 254, in set_input
    self._set_inoutput_item(item)
  File "/home/user/miniconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/rules.py", line 470, in _set_inoutput_item
    "Input and output files have to be specified as strings or lists of strings.")
  File "<string>", line None
SyntaxError: Input and output files have to be specified as strings or lists of strings.

SyntaxError:
Input and output files have to be specified as strings or lists of strings.
  File "/mnt/stripe/rcherniatchik/_playground/pipeline/sources2/Snakefile", line 78, in <module>
```

**Comment by iromeo** [comment]
Done
![image](https://user-images.githubusercontent.com/72933/90028893-e4495a00-dcc2-11ea-9f85-7386f1b0de38.png)
