### ISSUE TITLE
Analyze stacktrace doesn't highlight python paths as hyper links

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#267]
```
INPUT COV HIST: qc/npz_cpg/merged_consensus_cov/consensus_hs37d5_cpg.ind1_avg10.cov.hist.tsv
INPUT COV SUMMARY: qc/npz_cpg/merged_consensus_cov/consensus_hs37d5_cpg.ind1_avg10.cov.summary.tsv
OUTPUT BASENAME: qc/npz_cpg/merged_consensus_cov/consensus_hs37d5_cpg.ind1_avg10.plot
PLOT TITLE PREFIX: Merged +/- CpG consensus mincov(ind 1, avg 10):
PLOT WIDTH: 1400
PLOT HEIGHT: 800
Result saved to: qc/npz_cpg/merged_consensus_cov/consensus_hs37d5_cpg.ind1_avg10.plot.cov.html
Traceback (most recent call last):
  File "scripts/summary_plots_methylation.py", line 192, in <module>
    _cli()
  File "scripts/summary_plots_methylation.py", line 82, in _cli
    plot_height, plot_width
  File "scripts/summary_plots_methylation.py", line 106, in plot_cov_dist
    max_y = np.max(df1.values)
  File "<__array_function__ internals>", line 6, in amax
  File "/mnt/stripe/rcherniatchik/_playground/results_small2/.snakemake/conda/3c59c2c8/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2621, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/mnt/stripe/rcherniatchik/_playground/results_small2/.snakemake/conda/3c59c2c8/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

```

![image](https://user-images.githubusercontent.com/72933/68528270-8e91ec80-0301-11ea-8ab6-9c3de9e58ddf.png)

**Comment by iromeo** [comment]
PyCharm `PythonTracebackFilter` works ok for *.py files in 2020.2 EAPs and doesn't work in 2020.1.3

![image](https://user-images.githubusercontent.com/72933/87330581-77b33200-c541-11ea-9b05-4c5bf8fea8b6.png)

Also works in `Terminal` toolwindow:
![image](https://user-images.githubusercontent.com/72933/87331062-163f9300-c542-11ea-8bfc-3210cbcebcc5.png)

**Comment by iromeo** [comment]
At the moment the feature already works, let's reopen this issue if some additional behavior is desired.

**Comment by iromeo** [comment]
Also could be useful EP: `com.intellij.consoleFilterProvider`
