### ISSUE TITLE
SnakeCharm is not compatible with AppCode - Fatal error initializing 'com.intellij.psi.impl.cache.impl.id.IdIndexImpl' appears 

### ISSUE THREAD

**Issue by olesyabogdanova** [JetBrains-Research/snakecharm#269]
Reproduced with AppCode 2019.3 EAP,  build #OC-193.5233.58, built on November 20, 2019

SnakeCharm mark as compatible with all IntelliJ-based IDEs

Steps:
1. Open any project in AppCode
2. Install SnakeCharm
3. Restart IDE

AC: 
- com.intellij.ide.plugins.StartupAbortedException: Fatal error initializing 'com.intellij.psi.impl.cache.impl.id.IdIndexImpl' appears after installation in AppCode 
- there isn't ability open existed project, create new. Available only welcome page. If project ws opened before installation - it is closed after restart.

**Comment by olesyabogdanova** [comment]
Stack trace:
com.intellij.ide.plugins.StartupAbortedException: Fatal error initializing 'com.intellij.psi.impl.cache.impl.id.IdIndexImpl'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:58)
	at com.intellij.util.indexing.FileBasedIndexImpl$FileIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexImpl.java:2454)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.executeNestedInitializationTask(IndexInfrastructure.java:173)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.runParallelNestedInitializationTasks(IndexInfrastructure.java:161)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.call(IndexInfrastructure.java:122)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.diagnostic.PluginException: While loading class com.jetbrains.snakecharm.SmkFileType: com/jetbrains/python/PythonFileType [Plugin: SnakeCharm]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:223)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:167)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:474)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiatePendingFileTypes(FileTypeManagerImpl.java:464)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getRegisteredFileTypes(FileTypeManagerImpl.java:1269)
	at com.intellij.psi.impl.cache.impl.id.IdIndexImpl.getVersion(IdIndexImpl.java:25)
	at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:349)
	at com.intellij.util.indexing.FileBasedIndexImpl.access$5300(FileBasedIndexImpl.java:107)
	at com.intellij.util.indexing.FileBasedIndexImpl$FileIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexImpl.java:2448)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: com/jetbrains/python/PythonFileType
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:359)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:355)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:319)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:220)
	... 24 more
Caused by: java.lang.ClassNotFoundException: com.jetbrains.python.PythonFileType PluginClassLoader[SnakeCharm, 0.5.112.2018.3] com.intellij.ide.plugins.cl.PluginClassLoader@4c449864
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 31 more

**Comment by iromeo** [comment]
Dependency on `python plugin` fixed (not optional anymore), so this plugin becomes not compatible with AppCode. Plugin update 0.5.1.126 released, the wrong build removed from the repository.
