### ISSUE TITLE
`Outdated stub in index:` exception

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#349]
May be caused:
1) set custom interpreter in snakemake settings (not project one)
2) updated the interpreter using terminal snakemake version
3) resolve/completion issues for interpreter sdk methods

Vers: 0.10.0.SNAPSHOT
```
Outdated stub in index: file:///Users/romeo/anaconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/workflow.py indexing timestamp = 1588857159000, binary = false, byte size = 51139, char size = 51137, doc=DocumentImpl[file:///Users/romeo/anaconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/workflow.py], docSaved=true, wasIndexedAlready=true, queried at 1608588946000
doc length=57441
file length=57443
cached PSI class com.jetbrains.python.psi.impl.PyFileImpl
projects with file: 1
physical file exists; length = 57443

java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:177)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:143)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:105)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:59)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:201)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:149)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:216)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:734)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:128)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getFirstChild(ASTDelegatePsiElement.java:99)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:67)
	at com.jetbrains.snakecharm.codeInsight.ImplicitPySymbolsProvider.collectWorkflowGlobalVariables(ImplicitPySymbolsProvider.kt:481)
	at com.jetbrains.snakecharm.codeInsight.ImplicitPySymbolsProvider.access$collectWorkflowGlobalVariables(ImplicitPySymbolsProvider.kt:38)
	at com.jetbrains.snakecharm.codeInsight.ImplicitPySymbolsProvider$onChange$1$$special$$inlined$runReadAction$1.compute(actions.kt:70)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:871)
	at com.jetbrains.snakecharm.codeInsight.ImplicitPySymbolsProvider$onChange$1.run(ImplicitPySymbolsProvider.kt:545)
	at com.intellij.openapi.project.DumbServiceImpl.doUnsafeRunWhenSmart(DumbServiceImpl.java:254)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:240)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runAfterOpened(StartupManagerImpl.java:481)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:240)
	at com.jetbrains.snakecharm.codeInsight.ImplicitPySymbolsProvider.onChange(ImplicitPySymbolsProvider.kt:79)
	at com.jetbrains.snakecharm.codeInsight.ImplicitPySymbolsProvider.access$onChange(ImplicitPySymbolsProvider.kt:38)
	at com.jetbrains.snakecharm.codeInsight.ImplicitPySymbolsProvider$scheduleUpdate$1.run(ImplicitPySymbolsProvider.kt:57)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by iromeo** [comment]
seems obsolete
