### ISSUE TITLE
Update/Install/Uninstall plugin w/o IDE restart

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#356]
Not always work, e.g on update:

```
2021-04-24 17:12:00,837 [     79]   INFO -        #com.intellij.idea.Main - JVM: 11.0.10+9-b1341.41 (Dynamic Code Evolution 64-Bit Server VM) 
2021-04-24 21:13:19,074 [14478316]   INFO - lij.ide.plugins.DynamicPlugins - Plugin SnakeCharm is not unload-safe because class loader cannot be unloaded 
2021-04-24 21:13:21,144 [     77]   INFO -        #com.intellij.idea.Main - JVM: 11.0.10+9-b1341.41 (Dynamic Code Evolution 64-Bit Server VM) 
2021-04-24 21:14:33,914 [  72847]   INFO - lij.ide.plugins.DynamicPlugins - Can't read descriptor withJavaPlugin.xml for optional dependency of plugin being loaded/unloaded 
2021-04-24 21:14:34,006 [  72939]   INFO - lij.ide.plugins.DynamicPlugins - Plugin SnakeCharm loaded without restart in 183 ms 
2021-04-24 21:58:56,607 [     65]   INFO -        #com.intellij.idea.Main - JVM: 11.0.10+9-b1341.41 (Dynamic Code Evolution 64-Bit Server VM) 
	at com.intellij.ide.plugins.DynamicPlugins.unloadPluginDescriptorNotRecursively(DynamicPlugins.kt:721)
	at com.intellij.ide.plugins.DynamicPlugins.access$unloadPluginDescriptorNotRecursively(DynamicPlugins.kt:103)
	at com.intellij.ide.plugins.DynamicPlugins$unloadPlugin$2.run(DynamicPlugins.kt:488)
	at com.intellij.ide.plugins.DynamicPlugins.unloadPlugin(DynamicPlugins.kt:474)
	at com.intellij.ide.plugins.DynamicPlugins$unloadPluginWithProgress$2.run(DynamicPlugins.kt:401)
	at com.intellij.ide.plugins.DynamicPlugins.unloadPluginWithProgress(DynamicPlugins.kt:400)
	at com.intellij.ide.plugins.PluginInstaller.uninstallDynamicPlugin(PluginInstaller.java:124)
2021-04-24 22:00:01,353 [  64811]   INFO - lij.ide.plugins.DynamicPlugins - Plugin SnakeCharm is not unload-safe because class loader cannot be unloaded 


2021-04-24 22:01:07,714 [     57]   INFO -        #com.intellij.idea.Main - JVM: 11.0.10+9-b1341.41 (Dynamic Code Evolution 64-Bit Server VM) 
```

```
2021-04-24 21:58:57,443 [    901]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: IdeaVim (0.66), SnakeCharm (0.11.0.410) 
2021-04-24 21:59:55,272 [  58730]   WARN - tions.ex.ConfigurableCardPanel - auto-dispose 'Snakemake' id=com.jetbrains.snakecharm.framework.SmkFrameworkConfigurableProvider 
2021-04-24 22:00:01,353 [  64811]   INFO - lij.ide.plugins.DynamicPlugins - Plugin SnakeCharm is not unload-safe because class loader cannot be unloaded 
2021-04-24 22:01:08,460 [    803]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: IdeaVim (0.66), SnakeCharm (0.11.0.411) 
```

**Comment by iromeo** [comment]
See https://plugins.jetbrains.com/docs/intellij/dynamic-plugins.html#diagnosing-leaks
