### ISSUE TITLE
'shell' section: resolve & completion for `params` args

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#43]
'shell' section: resolve & completion for `params` args

```
rule call_peaks_span_all:
    input:
        bam="cleaned_all/pooled.bam",
        span=rules.download_span.output,
        chrom_sizes=rules.download_chrom_sizes.output
    output: "cleaned_all_peaks/span/pooled_{bin, [0-9]+}.span"
    params:
        outdir=lambda wildcards, output: os.path.dirname(str(output)),
        xmx=lambda wildcards: str(800 // int(wildcards.bin))
    threads: 8
    shell: 'java -Xmx{params.xmx}G  -jar {input.span} analyze -t {input.bam} --workdir {params.outdir} --fragment 0 ' \
           '--bin {wildcards.bin} --cs {input.chrom_sizes} --threads {threads} --model {output} --keep-dup true --debug; '\
           '--foo {params.}'
```

* Auto-complete keyword args names after `params.` in shell section. E.g.
![2019-05-11_18-20-29](https://user-images.githubusercontent.com/72933/57572609-79590580-7425-11e9-967a-b4049cb3ac96.png)

* Resolve keyword args names, e.g. `xmx` in `{params.xmx}` into `params:` section

**Comment by iromeo** [comment]
Merged in master, feature throws an exception:
```
rule foo:
    params: 1, ff=1, bb=2
    shell: "ffo {params.} boo"
```

```
kotlin.KotlinNullPointerException
	at com.jetbrains.snakecharm.lang.psi.SMKParamsReference.getVariants(SMKParamsReference.kt:34)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:274)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:137)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:82)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.lambda$completeReference$0(LegacyCompletionContributor.java:71)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReference(LegacyCompletionContributor.java:125)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:108)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:69)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:52)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsig
```
