### ISSUE TITLE
 'this constructor' is deprecated and going to be removed soon.

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#435]
Occurred in:
```
DataSpell 2021.3 EAP 20
Build #PD-213.5352.7, built on October 26, 2021
DataSpell EAP User
Expiration date: December 10, 2021
Runtime version: 11.0.12+7-b1751.3 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2500M
Cores: 16
Registry:
    python.scientific.show_help_window=false
    python.scientific.always_use_sci_view=true

Non-Bundled Plugins:
    SnakeCharm (2021.2.424-eap)
```

```
java.lang.Throwable: 'this constructor' is deprecated and going to be removed soon. 
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:105)
	at com.jetbrains.python.inspections.PyInspectionVisitor.<init>(PyInspectionVisitor.java:52)
	at com.jetbrains.snakecharm.inspections.SnakemakeInspectionVisitor.<init>(SnakemakeInspectionVisitor.kt:12)
	at com.jetbrains.snakecharm.inspections.SmkSectionMultipleArgsInspection$buildVisitor$1.<init>(SmkSectionMultipleArgsInspection.kt:16)
	at com.jetbrains.snakecharm.inspections.SmkSectionMultipleArgsInspection.buildVisitor(SmkSectionMultipleArgsInspection.kt:16)
	at com.jetbrains.snakecharm.inspections.SmkSectionMultipleArgsInspection.buildVisitor(SmkSectionMultipleArgsInspection.kt:11)
	at com.intellij.codeInspection.InspectionEngine.createVisitor(InspectionEngine.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.createContext(LocalInspectionsPass.java:474)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:349)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1934)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:349)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:227)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:127)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by iromeo** [comment]
Also check deprecated API: https://plugins.jetbrains.com/plugin/11947-snakecharm/versions/eap/143830
