### ISSUE TITLE
Exception: "Access is allowed from write thread only" creating project in dumb mode

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#506]
```
Access is allowed from write thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Current thread: Thread[DefaultDispatcher-worker-4,5,main] 1632415832 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 388826321
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1050)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertWriteIntentLockAcquired(ApplicationImpl.java:1064)
	at com.intellij.openapi.application.impl.ApplicationImpl.startWrite(ApplicationImpl.java:1146)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:956)
	at com.jetbrains.snakecharm.framework.SmkSupportProjectSettings$Companion.updateStateAndFireEvent(SmkFrameworkProjectSettings.kt:155)
	at com.jetbrains.snakecharm.framework.SmkSupportProjectSettings$Companion.addSupport(SmkFrameworkProjectSettings.kt:145)
	at com.jetbrains.snakecharm.framework.SmkFrameworkSupportDirProjectConfigurator.enableSnakemakeSupport(SmkFrameworkSupportDirProjectConfigurator.kt:58)
	at com.jetbrains.snakecharm.framework.SmkFrameworkSupportDirProjectConfigurator.configureProject$lambda-1$lambda-0(SmkFrameworkSupportDirProjectConfigurator.kt:32)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runActivities$3$1.invoke(StartupManagerImpl.kt:375)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runActivities$3$1.invoke(StartupManagerImpl.kt:374)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:193)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivities(StartupManagerImpl.kt:374)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesRegisteredDynamically(StartupManagerImpl.kt:344)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:296)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:69)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:178)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)


```

**Comment by iromeo** [comment]
Done

**Comment by iromeo** [comment]
Done
