### ISSUE TITLE
NoClassDefFoundError: com/intellij/psi/util/PsiTreeUtilKt

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#70]
```
PyCharm 2019.1.3 (Professional Edition)
Build #PY-191.7479.30, built on May 29, 2019
Licensed to JetBrains Team / Roman Chernyatchik
Subscription is active until December 10, 2019
JRE: 11.0.2+9-b159.60 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14
```

```
java.lang.NoClassDefFoundError: com/intellij/psi/util/PsiTreeUtilKt
	at com.jetbrains.snakecharm.codeInsight.completion.SMKImplicitPySymbolsCompletionContributor$Companion$REF_CAPTURE$1.accepts(SMKImplicitPySymbolsCompletionContributor.kt:59)
	at com.jetbrains.snakecharm.codeInsight.completion.SMKImplicitPySymbolsCompletionContributor$Companion$REF_CAPTURE$1.accepts(SMKImplicitPySymbolsCompletionContributor.kt:21)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:68)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:160)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:90)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:77)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:161)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:90)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:120)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:60)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:828)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:813)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:280)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:277)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by iromeo** [comment]
Fixed.

Post-mortem: Don't use `com.intellij.psi.util.parentOfType` extension method from `com/intellij/psi/util/psiTreeUtil.kt` in non-java plugins. E.g. this API isn't available in PyCharm and other non-java IDE's, so you could get such java.lang.NoClassDefFoundError error on runtime. Use `PsiTreeUtil.getParentOfType(..)` instead.

P.S: Maybe the API will be moved in platform core some day, see https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000764084-ClassNotFoundException-for-PsiTreeUtilKt-in-WebStorm.

**Comment by iromeo** [comment]
Seems still cannot use `com.intellij.psi.util.parentOfType` even if depend on IDE kotlin libraries. So need cleanup again.

**Comment by iromeo** [comment]
Obsolete, we don't use `com.intellij.psi.util.parentOfType` any more
